---
- name: Deploy Prometheus using Docker
  hosts: targets
  become: yes
  tasks:
    - name: Install required packages
      yum:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install requests Python library
      ansible.builtin.pip:
        name: requests
        state: present

    - name: Ensure Prometheus configuration directory exists
      ansible.builtin.file:
        path: /etc/prometheus/
        state: directory
        mode: '0777'

    - name: Ensure Prometheus configuration directory exists
      ansible.builtin.file:
        path: /prometheus/
        state: directory
        mode: '0777'

    - name: Create Prometheus configuration file
      ansible.builtin.copy:
        dest: /etc/prometheus/prometheus.yml
        content: |
          global:
            scrape_interval:     15s # By default, scrape targets every 15 seconds.
            evaluation_interval: 15s # Evaluate rules every 15 seconds.
          scrape_configs:
            - job_name: 'prometheus'
              static_configs:
                - targets: ['localhost:9090']

    - name: Pull the Prometheus Docker image
      community.docker.docker_image:
        name: "prom/prometheus"
        source: pull

    - name: Run Prometheus Docker container
      community.docker.docker_container:
        name: prometheus
        image: prom/prometheus
        state: started
        restart_policy: always
        ports:
          - "9090:9090"
        volumes:
          - "/etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
#          - "/prometheus:/prometheus"

