---
- name: Install Docker on a RPM-based system
  hosts: targets
  become: yes  # This is required to gain root privileges
  tasks:
    - name: Ensure NTP synchronization is enabled
      ansible.builtin.command:
        cmd: chronyc -a makestep
    - ansible.builtin.command:
        cmd: systemctl restart chronyd

    - name: Install required packages
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present

    - name: Add Docker repository
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: Install Docker
      yum:
        name: docker-ce
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: true
